version: "3.9"

services:
  app:
    image: ghcr.io/adzi007/notif-service-app:latest
    networks:
      - ecommerce-network
    depends_on:
      - db
    ports:
      - "5002:5002"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    deploy:
      replicas: 2  # Run 2 instances across worker nodes
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
      placement:
        constraints:
          - node.role == worker

networks:
  ecommerce-network:
    driver: overlay
