version: "3.9"

services:
  db:
    image: mysql:8
    container_name: ecommerce-notification-db
    networks:
      - ecommerce-network
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD} 
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - "3308:3306" 
    volumes:
      - db_notif_data:/var/lib/mysql
    env_file:
      - .env 
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: ecommerce-notification-service
    networks:
      - ecommerce-network
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${PORT_APP}:${PORT_APP}"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    env_file:
      - .env 

networks:
  ecommerce-network:
    external: true

volumes:
  db_notif_data: