version: "3.9"

services:
  db:
    image: mysql:latest
    networks:
      - ecommerce-network
    environment:
      - MYSQL_ROOT_PASSWORD=KopiJoni888
      - MYSQL_DATABASE=ecommerce_development
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    deploy:
      placement:
        constraints:
          - node.role == manager
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: ghcr.io/adzi007/notif-service-app:latest
    networks:
      - ecommerce-network
    depends_on:
      - db
    ports:
      - "5002:5002"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=KopiJoni888
      - DB_NAME=ecommerce_development
    env_file:
      - .env
    deploy:
      replicas: 2  # Run 2 instances across worker nodes
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
      placement:
        constraints:
          - node.role == worker
    # entrypoint: ["/bin/sh", "-c", "until mysqladmin ping -h db --silent; do echo waiting for database; sleep 2; done; exec ./main"]

networks:
  ecommerce-network:
    driver: overlay  # No need to create it manually

volumes:
  db_data:
