version: "3.9"

services:
  db:
    image: mysql:latest
    container_name: ecommerce-notification-db
    networks:
      - ecommerce-network
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD} 
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    deploy:
      placement:
        constraints:
          - node.role == manager
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: registry.gitlab.com/belajar1301942/ecommerce-notification-service:latest
    networks:
      - ecommerce-network
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5002:5002"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    env_file:
      - .env
    deploy:
      replicas: 2  # Run 2 instances across worker nodes
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
      placement:
        constraints:
          - node.role == worker

networks:
  ecommerce-network:
    external: true

volumes:
  db_data:
